language: node_js

node_js:
    - "5.7.0"

env:
    - CXX=g++-4.8

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8

before_install:
    - npm install -g protractor

install:
    - npm install -g npm@2
    - npm install -g grunt-cli
    - npm install -g bower
    - bower install
    - npm install
    - ./node_modules/protractor/bin/webdriver-manager update --standalone

before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - npm run build
    - npm test
    - grunt e2e-test
